#!/bin/bash -login
#SBATCH --nodes=1
#SBATCH --gres=gpu:2
#SBATCH --partition=gpu
#SBATCH --job-name=de-8
#SBATCH --mem=9000M

module load languages/anaconda3/2020.02-tflow-2.2.0

cd $SLURM_SUBMIT_DIR

python de2en.py 8